import { Metadata } from 'next';

import { PokeApi, PokemonGrid } from '@/pokemons';

export const metadata: Metadata = {
  title: 'Favoritos',
  description: 'Generated by create next app',
};

export default async function PokemonsPage() {
  return (
    <div className='flex flex-col'>
      <span className='text-5xl my-2'>
        Pokémons Favoritos <small className='text-blue-500'>Global State</small>
        <PokemonGrid pokemons={[]} />
      </span>
    </div>
  );
}
